name: Run test for Cryptopals challenges

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch, challenge57 ]

jobs:
  common-packages:
    name: Run tests for common packages
    runs-on: ubuntu-latest
    stragegy:
      matrix:
        packages: [dh, helpers]
    steps:
      - name: Checkout
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Test
        run: go test -v -count=1 ./${{ matrix.packages }}
