name: Run test for Cryptopals challenges

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  common-packages:
    name: Run tests for common packages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        packages: [ dh, helpers ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Run tests for package `${{ matrix.packages }}'
        run: go test -v -count=1 ./${{ matrix.packages }}

  challenges:
    name: Run tests for challenges
    runs-on: ubuntu-latest
    strategy:
      matrix:
        challenges: [ challenge57, challenge58 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Run tests for challenge `${{ matrix.challenges }}'
        run: go test -v -count=1 ./${{ matrix.challenges }}
