name: Run test for Cryptopals challenges

env:
  GOLANG_VER: 1.15

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch, challenge57]

jobs:
  common-packages:
    name: Run tests for common packages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        packages: [dh, helpers]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: GOLANG_VER

      - name: Run tests for package `${{ matrix.packages }}'
        run: go test -v -count=1 ./${{ matrix.packages }}

  challenge57:
    name: Run tests for challenge 57
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: GOLANG_VER

      - name: Run tests for challenge 57
        run: go test -v -count=1 ./challenge57
